import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { CLAIM_LETTER_SECTION_KEYS } from "@/lib/claims-anthropic";

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica", lineHeight: 1.5, color: "#1A1D24" },
  header: { marginBottom: 18, borderBottom: "1 solid #E2E4E9", paddingBottom: 14 },
  title: { fontSize: 14, fontWeight: 700, marginBottom: 3 },
  meta: { fontSize: 9.5, color: "#5B616E" },
  body: { fontSize: 11 },
  sectionLabel: { fontSize: 9, fontWeight: 700, color: "#5B616E", marginTop: 12, marginBottom: 3, textTransform: "uppercase" },
  sectionContent: { fontSize: 11 },
  footer: { position: "absolute", bottom: 30, left: 48, right: 48, fontSize: 8, color: "#9AA0AC" },
});

export function ClaimLetterPdfDocument({
  claimNumber,
  patientLabel,
  payer,
  content,
  sections,
}: {
  claimNumber: string;
  patientLabel: string;
  payer: string;
  content: string;
  sections?: Record<string, { label: string; content: string }> | null;
}) {
  const sectionList = sections
    ? CLAIM_LETTER_SECTION_KEYS.filter((key) => sections[key]).map((key) => sections[key])
    : null;

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Claims Appeal Letter</Text>
          <Text style={styles.meta}>
            {patientLabel} · Claim {claimNumber || "(none)"} · {payer || "Payer not specified"}
          </Text>
        </View>
        <View style={styles.body}>
          {sectionList
            ? sectionList.map((section, i) => (
                <View key={i}>
                  <Text style={styles.sectionLabel}>{section.label}</Text>
                  {section.content.split("\n").map((line, j) => (
                    <Text key={j} style={[styles.sectionContent, { marginBottom: line.trim() === "" ? 6 : 2 }]}>
                      {line || " "}
                    </Text>
                  ))}
                </View>
              ))
            : content.split("\n").map((line, i) => (
                <Text key={i} style={{ marginBottom: line.trim() === "" ? 6 : 2 }}>
                  {line || " "}
                </Text>
              ))}
        </View>
        <Text style={styles.footer} fixed>
          Generated by asaanbil.com — drafted for staff review, not a final submission until approved.
        </Text>
      </Page>
    </Document>
  );
}
