import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica", lineHeight: 1.5, color: "#1A1D24" },
  header: { marginBottom: 18, borderBottom: "1 solid #E2E4E9", paddingBottom: 14 },
  title: { fontSize: 14, fontWeight: 700, marginBottom: 3 },
  meta: { fontSize: 9.5, color: "#5B616E" },
  body: { fontSize: 11 },
  footer: { position: "absolute", bottom: 30, left: 48, right: 48, fontSize: 8, color: "#9AA0AC" },
});

export function LetterPdfDocument({
  patientReference,
  procedureLabel,
  payer,
  content,
}: {
  patientReference: string;
  procedureLabel: string;
  payer: string;
  content: string;
}) {
  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>Prior Authorization Justification Letter</Text>
          <Text style={styles.meta}>
            {patientReference} · {procedureLabel} · {payer.replace(/_/g, " ")}
          </Text>
        </View>
        <View style={styles.body}>
          {content.split("\n").map((line, i) => (
            <Text key={i} style={{ marginBottom: line.trim() === "" ? 6 : 2 }}>
              {line || " "}
            </Text>
          ))}
        </View>
        <Text style={styles.footer} fixed>
          Generated by Clearway — drafted for physician review, not a final submission until approved by staff.
        </Text>
      </Page>
    </Document>
  );
}
