import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { Database } from "@/lib/database.types";

type PatientRow = Database["public"]["Tables"]["patients"]["Row"];

const styles = StyleSheet.create({
  page: { padding: 48, fontSize: 11, fontFamily: "Helvetica", lineHeight: 1.5, color: "#1A1D24" },
  header: { marginBottom: 18, borderBottom: "1 solid #E2E4E9", paddingBottom: 14 },
  title: { fontSize: 14, fontWeight: 700, marginBottom: 3 },
  meta: { fontSize: 9.5, color: "#5B616E" },
  sectionLabel: { fontSize: 9, fontWeight: 700, color: "#5B616E", marginTop: 14, marginBottom: 4, textTransform: "uppercase" },
  row: { flexDirection: "row", marginBottom: 3 },
  fieldLabel: { width: 160, fontSize: 10, color: "#5B616E" },
  fieldValue: { fontSize: 10.5, flex: 1 },
  footer: { position: "absolute", bottom: 30, left: 48, right: 48, fontSize: 8, color: "#9AA0AC" },
});

function Field({ label, value }: { label: string; value?: string | number | boolean | null }) {
  if (value === null || value === undefined || value === "") return null;
  return (
    <View style={styles.row}>
      <Text style={styles.fieldLabel}>{label}</Text>
      <Text style={styles.fieldValue}>{String(value)}</Text>
    </View>
  );
}

export function PatientPdfDocument({ patient }: { patient: PatientRow }) {
  const fullName = [patient.first_name, patient.middle_name, patient.last_name].filter(Boolean).join(" ");

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.title}>{fullName}</Text>
          <Text style={styles.meta}>{patient.patient_ref_id} · Internal reference only, never sent to a payer</Text>
        </View>

        <Text style={styles.sectionLabel}>Patient Identity</Text>
        <Field label="Date of birth" value={patient.dob} />
        <Field label="Gender" value={patient.gender} />
        <Field label="Status" value={patient.status} />
        <Field label="Preferred language" value={patient.preferred_language} />

        <Text style={styles.sectionLabel}>Contact</Text>
        <Field label="Address" value={[patient.address, patient.city, patient.state, patient.zip].filter(Boolean).join(", ")} />
        <Field label="Phone" value={patient.phone} />
        <Field label="Email" value={patient.email} />

        <Text style={styles.sectionLabel}>Primary Insurance</Text>
        <Field label="Insurance company" value={patient.insurance_company} />
        <Field label="Plan type" value={patient.plan_type} />
        <Field label="State of plan" value={patient.state_of_plan} />
        <Field label="Member ID" value={patient.member_id} />
        <Field label="Group number" value={patient.group_number} />
        <Field label="Plan name" value={patient.plan_name} />

        {patient.has_secondary_insurance && (
          <>
            <Text style={styles.sectionLabel}>Secondary Insurance</Text>
            <Field label="Insurance company" value={patient.secondary_insurance_company} />
            <Field label="Plan type" value={patient.secondary_plan_type} />
            <Field label="Member ID" value={patient.secondary_member_id} />
            <Field label="Group number" value={patient.secondary_group_number} />
          </>
        )}

        {(patient.primary_diagnosis_icd10 || patient.known_drug_allergies) && (
          <>
            <Text style={styles.sectionLabel}>Clinical</Text>
            <Field
              label="Primary diagnosis"
              value={[patient.primary_diagnosis_icd10, patient.primary_diagnosis_description].filter(Boolean).join(" — ")}
            />
            <Field label="Known drug allergies" value={patient.known_drug_allergies} />
            <Field label="Current medications" value={patient.current_medications} />
          </>
        )}

        <Text style={styles.footer} fixed>
          Generated by asaanbil.com — internal record, contains PHI. Handle per your practice&apos;s privacy policy.
        </Text>
      </Page>
    </Document>
  );
}
